#!/usr/bin/env bash

set -e -x
git --version

upstream=$3
branch=$2
host=$1
REPO=$4
: ${upstream:=origin}
: ${branch:=master}
: ${host:=data.transformap.co}
: ${REPO:=git@github.com:transformap/transformap-editor.git}
git fetch $upstream
if [ `git rev-list HEAD...$upstream/$branch --count` -ne 0 ]; then
  printf "# Not deploying.\n# Please update your upstream branch with your local commits before proceeding.\n"
  exit 1
fi

rm -rf public
# use --reference when not in shallow clone
# git clone $REPO --reference . -b dokku _public
git clone $REPO -b dokku public

rm -rf public/*
npm i
REV=`git describe --always`
BUILD=git-$REV FQDN=$host npm run compile
cd public
git remote add deploy dokku@apps.allmende.io:edit.transformap.co
git add -A .
echo "regen for $REV" | git commit-tree `git write-tree` -p `git rev-parse HEAD` -p $REV | xargs git reset --hard
git push origin dokku
git push -f deploy dokku:master
cd ..
